import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import * as FiIcons from 'react-icons/fi';
import SafeIcon from '../common/SafeIcon';
import Navigation from './Navigation';
import Footer from './sections/Footer';

const { FiArrowLeft, FiFileText } = FiIcons;

const TermsOfUsePage = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-white">
      <Navigation />
      
      {/* Hero Section */}
      <section className="pt-24 pb-16 bg-gradient-to-br from-emerald-50 to-blue-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <button
            onClick={() => navigate('/')}
            className="flex items-center space-x-2 text-emerald-600 hover:text-emerald-700 mb-8 transition-colors"
          >
            <SafeIcon icon={FiArrowLeft} className="w-5 h-5" />
            <span>Back to Home</span>
          </button>
          
          <div className="text-center max-w-4xl mx-auto">
            <div className="w-20 h-20 bg-emerald-100 rounded-2xl flex items-center justify-center mx-auto mb-6">
              <SafeIcon icon={FiFileText} className="w-10 h-10 text-emerald-600" />
            </div>
            <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
              Terms of Use
            </h1>
            <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
              Please read these terms carefully before using FoodAgri AI services
            </p>
          </div>
        </div>
      </section>

      {/* Terms Content */}
      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="prose prose-lg max-w-none"
          >
            <div className="bg-gray-50 rounded-2xl p-8 mb-8">
              <p className="text-sm text-gray-600 mb-4">
                <strong>Effective Date:</strong> June 25, 2025
              </p>
              <p className="text-sm text-gray-600 mb-4">
                <strong>Between:</strong><br />
                FoodAgri AI LLC, a Wyoming Limited Liability Company, 30 N Gould St Ste R, Sheridan, WY 82801 ("FoodAgri AI", "we", "us", or "our")<br />
                and<br />
                You, the individual or entity accessing or using the FoodAgri AI platform and services ("User", "you", or "your").
              </p>
            </div>

            <div className="space-y-12">
              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">1. Introduction and Acceptance</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  By accessing, browsing, or using the FoodAgri AI website, platform, or services, you agree to be bound by these Terms of Use and our{' '}
                  <button 
                    onClick={() => navigate('/privacy-policy')}
                    className="text-emerald-600 hover:text-emerald-700 underline font-medium"
                  >
                    Privacy Policy
                  </button>. You must be at least 18 years old or have legal capacity to enter into this Agreement. If you do not agree, do not use our services.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Your explicit acceptance by clicking "I Agree" (or similar) during account creation, subscription, or feature access, or continued use after notice of changes, constitutes acceptance. These Terms constitute a legally binding agreement.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">2. Definitions</h2>
                <ul className="space-y-3 text-gray-700">
                  <li><strong>"Services":</strong> AI-powered SaaS solutions including but not limited to AI Lead Generation & Qualification, AI Content Creation & Marketing Automation, AI Sales Call Review & Coaching, AI Customer Service Automation, AI Data Analysis & Reporting, Compliance & Traceability Automation, Client Onboarding & Support, and Additional AI Solutions.</li>
                  <li><strong>"Platform":</strong> The FoodAgri AI software and infrastructure.</li>
                  <li><strong>"User Content":</strong> Data or content you upload or provide.</li>
                  <li><strong>"AI-Generated Outputs":</strong> Reports, analyses, or content generated by our AI models.</li>
                  <li><strong>"Personal Data":</strong> Information relating to an identified or identifiable person.</li>
                  <li><strong>"Third-Party Services":</strong> Services from vendors used by FoodAgri AI.</li>
                  <li><strong>"Governing Law":</strong> Laws of the State of Wyoming, USA, except as required by mandatory data privacy laws.</li>
                </ul>
                <p className="text-gray-700 leading-relaxed mt-4">
                  Definitions in our{' '}
                  <button 
                    onClick={() => navigate('/privacy-policy')}
                    className="text-emerald-600 hover:text-emerald-700 underline font-medium"
                  >
                    Privacy Policy
                  </button>{' '}
                  are incorporated by reference.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">3. Website Access and Use</h2>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li>Access is permitted only for users aged 18 or older.</li>
                  <li>FoodAgri AI LLC reserves the right to deny access to any person or entity for any reason, at its sole discretion, and to block or terminate any account or usage without notice.</li>
                  <li>No content, code, design, or materials may be copied, reproduced, published, distributed, or transmitted in any form or by any means without express written consent.</li>
                  <li>You may not hyperlink to, frame, or reference this website or its content in any commercial or public setting without prior written permission.</li>
                  <li>All subscriptions are for a minimum of 30 days unless otherwise agreed in writing. Refunds are not provided except as required by law or as specified in a separate agreement.</li>
                  <li>FoodAgri AI LLC makes no warranties regarding the accuracy, completeness, or reliability of any content, AI-generated output, or information provided. Use of the website and services is at your own risk.</li>
                  <li>FoodAgri AI LLC is not responsible for any damage to your computer, device, or data resulting from your use of the website, downloads, or interactions with any content or advertising.</li>
                  <li>By using this website and services, you waive all rights to claims of damage of any description except as expressly provided in these Terms. You agree to indemnify and hold harmless FoodAgri AI LLC from any claims, damages, or losses arising from your use, misuse, or violation of these Terms.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">4. Services Offered</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  FoodAgri AI LLC provides scalable AI-powered SaaS solutions for food and agriculture businesses, including:
                </p>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li><strong>AI Lead Generation & Qualification:</strong> Automated prospecting, segmentation, scoring, and outreach.</li>
                  <li><strong>AI Content Creation & Marketing Automation:</strong> Automated content generation and campaign scheduling.</li>
                  <li><strong>AI Sales Call Review & Coaching:</strong> Analysis and feedback on sales calls.</li>
                  <li><strong>AI Customer Service Automation:</strong> Automated 24/7 customer inquiries with multilingual support.</li>
                  <li><strong>AI Data Analysis & Reporting:</strong> Real-time dashboards and predictive analytics.</li>
                  <li><strong>Compliance & Traceability Automation:</strong> Automated documentation and reporting for compliance.</li>
                  <li><strong>Client Onboarding & Support:</strong> Automated onboarding workflows and AI-powered support.</li>
                  <li><strong>Additional AI Solutions:</strong> Advertising automation, workflow optimization, and more.</li>
                </ul>
                <p className="text-gray-700 leading-relaxed mt-4">
                  A current list of features is available at [insert URL]. We may update, modify, or discontinue services with 30 days' notice.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">5. User Responsibilities</h2>
                <p className="text-gray-700 leading-relaxed mb-4">You agree to:</p>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li>Maintain account security and notify us of unauthorized access.</li>
                  <li>Use the platform in compliance with all laws and our Acceptable Use Policy.</li>
                  <li>Ensure all data you provide is accurate and that you have rights to use it.</li>
                  <li>Independently verify AI-generated outputs before relying on them.</li>
                  <li>Not misuse the platform or outputs for unlawful, harmful, or competitive purposes.</li>
                  <li>Obtain all necessary consents for personal data you upload.</li>
                </ul>
                <p className="text-gray-700 leading-relaxed mt-4">
                  Breach may result in suspension or termination.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">6. Intellectual Property Rights</h2>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li>All platform IP is owned by FoodAgri AI LLC. You receive a limited, non-exclusive, non-transferable, revocable license for internal business use.</li>
                  <li>You retain ownership of your data but grant us a license to use it for service provision.</li>
                  <li>AI-generated outputs are for your internal use only; all rights to underlying algorithms and technology remain with FoodAgri AI LLC.</li>
                  <li>You may not reverse engineer, copy, modify, distribute, or use the platform to build competing products.</li>
                </ul>
                <p className="text-gray-700 leading-relaxed mt-4">
                  <strong>Third-Party Components:</strong> Some platform features use open-source or third-party libraries, subject to their own licenses. See [insert URL] for a current list.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">7. Data Privacy and Jurisdictional Compliance</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  FoodAgri AI LLC is committed to protecting user data and complying with all applicable data privacy laws, including but not limited to the California Consumer Privacy Act (CCPA), the General Data Protection Regulation (GDPR), and other relevant state, federal, and international regulations.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  While this Agreement is governed by the laws of the State of Wyoming, FoodAgri AI LLC will comply with mandatory data privacy and security requirements applicable to the personal data of users in other jurisdictions. In the event of a conflict between Wyoming law and any mandatory data privacy law (such as CCPA or GDPR), the applicable data privacy law will control solely with respect to the handling, processing, and protection of personal data covered by that law.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  For detailed information on how personal data is collected, used, stored, and protected, and on user rights under applicable data privacy laws, please refer to our{' '}
                  <button 
                    onClick={() => navigate('/privacy-policy')}
                    className="text-emerald-600 hover:text-emerald-700 underline font-medium"
                  >
                    Privacy Policy
                  </button>{' '}
                  and Data Processing Addendum, which are incorporated by reference into this Agreement.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Users are responsible for ensuring that any personal data they provide to FoodAgri AI LLC is collected and disclosed in compliance with applicable data privacy laws, including obtaining all necessary consents.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">8. Payment Terms</h2>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li>Payments are in USD via credit card or wire transfer.</li>
                  <li>Subscriptions auto-renew monthly unless canceled 7 days before renewal.</li>
                  <li>Late payments incur a 10% fee after 15 days.</li>
                  <li>Disputes must be reported within 7 days of billing; after this, charges are final.</li>
                  <li>No refunds except as specified in a separate agreement or for material breach by FoodAgri AI LLC.</li>
                  <li>You are responsible for all taxes.</li>
                  <li>We may update payment terms with 30 days' notice.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">9. Limitation of Liability</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  To the maximum extent permitted by law, FoodAgri AI LLC is not liable for indirect, incidental, special, consequential, punitive, or exemplary damages, including lost profits, data, or business interruption, even if advised of the possibility.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Our total liability is capped at the greater of six months' fees paid or $100, except where law prohibits.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Some jurisdictions do not allow certain limitations; only legally allowed limitations apply.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">10. Indemnification</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  You agree to indemnify, defend, and hold harmless FoodAgri AI LLC from any claims, damages, or losses arising from your misuse, breach of these Terms, or violation of law or third-party rights.
                </p>
                <p className="text-gray-700 leading-relaxed mb-4">
                  FoodAgri AI LLC indemnifies you only for its gross negligence or willful misconduct, subject to the liability cap in Section 9.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  Indemnification is subject to the liability cap unless prohibited by law.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">11. Termination and Data Export</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  Either party may terminate with notice. Upon termination, you have 30 days to access and export your data. After this period, FoodAgri AI LLC may delete all data associated with your account, except as required by law. If you fail to export data within this period, FoodAgri AI LLC will not be liable for any resulting loss. Additional details, including procedures for data export, secure deletion, retention exceptions, and transition assistance, are set forth in the{' '}
                  <button 
                    onClick={() => navigate('/data-handling-deletion-schedule')}
                    className="text-blue-600 hover:text-blue-700 underline font-medium"
                  >
                    Data Handling and Deletion Schedule
                  </button>
                  , incorporated herein by reference.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  We may suspend or terminate your access for breach, non-payment, or misuse.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">12. Dispute Resolution and Class Action Waiver</h2>
                <p className="text-gray-700 leading-relaxed mb-4">Disputes will be resolved by:</p>
                <ol className="space-y-2 text-gray-700 list-decimal ml-6">
                  <li>Good faith negotiation (30 days)</li>
                  <li>Mediation (45 days, via JAMS or similar provider)</li>
                  <li>Binding arbitration in Sheridan County, Wyoming, under JAMS rules (unless law requires otherwise).</li>
                </ol>
                <p className="text-gray-700 leading-relaxed mb-4">
                  <strong>Class Action Waiver:</strong> All disputes must be brought on an individual basis. You waive the right to participate in any class or representative action.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  If any part of this section is unenforceable in a jurisdiction, the remainder remains in effect.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">13. Disclaimer of Warranties</h2>
                <p className="text-gray-700 leading-relaxed mb-4">
                  FoodAgri AI LLC makes no warranties regarding the accuracy, completeness, or reliability of any content, AI-generated output, or information provided. Use of the website and services is at your own risk.
                </p>
                <p className="text-gray-700 leading-relaxed">
                  We are not responsible for any damage to your computer, device, or data resulting from your use of the website, downloads, or interactions with any content or advertising.
                </p>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">14. Miscellaneous</h2>
                <ul className="space-y-3 text-gray-700 list-disc ml-6">
                  <li><strong>Governing Law:</strong> Wyoming, except where mandatory data privacy or consumer protection laws apply.</li>
                  <li><strong>Severability:</strong> If any provision is invalid, the rest remain effective.</li>
                  <li><strong>Modification:</strong> We may update these Terms at any time. Users are responsible for keeping themselves informed of changes. Continued use of the website or services after changes constitutes acceptance.</li>
                  <li><strong>Assignment:</strong> You may not assign rights or obligations without our written consent.</li>
                  <li><strong>Entire Agreement:</strong> This document, together with the{' '}
                    <button 
                      onClick={() => navigate('/privacy-policy')}
                      className="text-emerald-600 hover:text-emerald-700 underline font-medium"
                    >
                      Privacy Policy
                    </button>, Acceptable Use Policy, Service Schedule, and{' '}
                    <button 
                      onClick={() => navigate('/data-handling-deletion-schedule')}
                      className="text-blue-600 hover:text-blue-700 underline font-medium"
                    >
                      Data Handling Schedule
                    </button>
                    , constitutes the entire agreement.</li>
                </ul>
              </section>

              <section>
                <h2 className="text-3xl font-bold text-gray-900 mb-6">15. Contact Information</h2>
                <p className="text-gray-700 leading-relaxed mb-4">For questions or legal notices, contact:</p>
                <p className="text-gray-700 leading-relaxed">
                  <a href="mailto:support@foodagriai.com" className="text-emerald-600 hover:text-emerald-700">support@foodagriai.com</a><br />
                  FoodAgri AI LLC, 30 N Gould St Ste R, Sheridan, WY 82801
                </p>
              </section>

              <div className="border-t border-gray-200 pt-8 mt-12">
                <p className="text-sm text-gray-500 italic">
                  Last updated: June 25, 2025
                </p>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default TermsOfUsePage;